-- 전체 삭제
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "DETAILOPTION" CASCADE CONSTRAINTS;
DROP TABLE "SPOTMATEDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "SPOTDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "POINTUSAGE" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "PLACE" CASCADE CONSTRAINTS;
DROP TABLE "USERREVIEW" CASCADE CONSTRAINTS;
DROP TABLE "USERS" CASCADE CONSTRAINTS;
DROP TABLE "CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "BRAND" CASCADE CONSTRAINTS;
DROP TABLE "COUPON" CASCADE CONSTRAINTS;
DROP TABLE "COUPONUSAGE" CASCADE CONSTRAINTS;
DROP TABLE "DETAILOPT" CASCADE CONSTRAINTS;
DROP TABLE "CAR" CASCADE CONSTRAINTS;
DROP TABLE "CARDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "SPOTMATE" CASCADE CONSTRAINTS;
DROP TABLE "RESERVATION" CASCADE CONSTRAINTS;
DROP TABLE "DRIVERREIVEW" CASCADE CONSTRAINTS;
DROP TABLE "DRIVERREVIEW" CASCADE CONSTRAINTS;

