-- 전체 삭제
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "DETAILOPTION" CASCADE CONSTRAINTS;
DROP TABLE "SPOTMATEDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "SPOTDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "POINTUSAGE" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "PLACE" CASCADE CONSTRAINTS;
DROP TABLE "USERREVIEW" CASCADE CONSTRAINTS;
DROP TABLE "USERS" CASCADE CONSTRAINTS;
DROP TABLE "CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "BRAND" CASCADE CONSTRAINTS;
DROP TABLE "COUPON" CASCADE CONSTRAINTS;
DROP TABLE "COUPONUSAGE" CASCADE CONSTRAINTS;
DROP TABLE "DETAILOPT" CASCADE CONSTRAINTS;
DROP TABLE "CAR" CASCADE CONSTRAINTS;
DROP TABLE "CARDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "SPOTMATE" CASCADE CONSTRAINTS;
DROP TABLE "RESERVATION" CASCADE CONSTRAINTS;
DROP TABLE "DRIVERREIVEW" CASCADE CONSTRAINTS;
DROP TABLE "DRIVERREVIEW" CASCADE CONSTRAINTS;

-- 시퀀스 전체삭제
SELECT * FROM USER_SEQUENCES;

DROP SEQUENCE seq_brand_no;
DROP SEQUENCE SEQ_CARDETAIL_NO;
DROP SEQUENCE SEQ_CARDETAIL_NO;
DROP SEQUENCE SEQ_CAR_NO;
DROP SEQUENCE SEQ_CATEGORY_NO;
DROP SEQUENCE SEQ_COUPONUSAGE_NO;
DROP SEQUENCE SEQ_COUPON_NO;
DROP SEQUENCE SEQ_DETAILOPTION_NO;
DROP SEQUENCE SEQ_DETAILOPT_NO;
DROP SEQUENCE SEQ_DRIVERREIVEW_NO;
DROP SEQUENCE SEQ_DRIVERREVIEW_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_PLACE_NO;
DROP SEQUENCE SEQ_POINTUSAGE_NO;
DROP SEQUENCE SEQ_RESERVATION_NO;
DROP SEQUENCE SEQ_SPOTDETAIL_NO;
DROP SEQUENCE SEQ_SPOTMATEDETAIL_NO;
DROP SEQUENCE SEQ_SPOTMATE_NO;
DROP SEQUENCE SEQ_USERREVIEW_NO;
DROP SEQUENCE SEQ_USERS_NO;
